CREATE TABLE OWNER (
  ownerID INT PRIMARY KEY AUTO_INCREMENT,
  surname VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  telephoneNumber VARCHAR(255) NOT NULL
);
CREATE TABLE PROPERTY (
  propertyID INT PRIMARY KEY AUTO_INCREMENT,
  size INT NOT NULL,
  address VARCHAR(255) NOT NULL,
  rentalPrice DECIMAL(10,2) NOT NULL,
  ownerID INT NOT NULL,
  FOREIGN KEY (ownerID) REFERENCES OWNER(ownerID)
);
CREATE TABLE LEASE (
  leaseID INT PRIMARY KEY AUTO_INCREMENT,
  propertyID INT NOT NULL,
  leaseNumber INT NOT NULL,
  leasePeriod DATE NOT NULL,
  tenantID INT NOT NULL,
  FOREIGN KEY (propertyID) REFERENCES PROPERTY(propertyID),
  FOREIGN KEY (tenantID) REFERENCES TENANT(tenantID)
);
CREATE TABLE TENANT (
  tenantID INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  telephoneNumber VARCHAR(255) NOT NULL
);
CREATE TABLE CONTRACT (
  contractID INT PRIMARY KEY AUTO_INCREMENT,
  propertyID INT NOT NULL,
  duration DATE NOT NULL,
  percentage DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (propertyID) REFERENCES PROPERTY(propertyID)
);
